/**
 * Fi Sabilillah — the responsive brand mark.
 *
 * GENERATED by tools/brand/build.py. Do not edit; edit the geometry and re-run.
 *
 * NOTE ON STATUS. There is no web client in this repository -- the product is a
 * native Kotlin/Compose Android application -- so nothing currently imports this.
 * It exists so a future web or PWA client starts from the identity rather than
 * re-tracing it.
 */
import * as React from "react";

export type LogoVariant =
  | "icon"
  | "horizontal"
  | "stacked"
  | "wordmark"
  | "compact"
  | "monochrome";

export type LogoTone = "full" | "dark" | "light" | "gold" | "monochrome";

export type LogoSize = "xs" | "sm" | "md" | "lg" | "xl" | "hero";

const EMBLEM_HEIGHT: Record<LogoSize, number> = {
  xs: 16,
  sm: 24,
  md: 40,
  lg: 64,
  xl: 96,
  hero: 160,
};

/**
 * Below this the keyline, the star and the leaf sweeps are under a pixel wide,
 * and the mark switches to its small cut.
 */
const SIMPLIFY_BELOW = 32;

const ARCH = "M32 4 C39.4 11.4 45.6 18.8 45.6 27.4 L45.6 40.4 C45.6 46.6 39.8 51.4 32 53.2 C24.2 51.4 18.4 46.6 18.4 40.4 L18.4 27.4 C18.4 18.8 24.6 11.4 32 4 Z";
const ARCH_KEYLINE = "M32 9.2 C38.2 15.6 42.4 21.4 42.4 27.8 L42.4 39.8 C42.4 44.6 37.8 48.4 32 49.9 C26.2 48.4 21.6 44.6 21.6 39.8 L21.6 27.8 C21.6 21.4 25.8 15.6 32 9.2 Z";
const CRESCENT = "M33.845 12.806 A6.4 6.4 0 1 0 33.845 23.594 A5.4 5.4 0 0 1 33.845 12.806 Z";
const STAR = "M37.9 12.4 L38.75 14.75 L41.25 14.83 L39.3 16.4 L39.98 18.8 L37.9 17.36 L35.82 18.8 L36.5 16.4 L34.55 14.83 L37.05 14.75 Z";
const ARCADE = "M22.60 46.60 L22.60 35.97 C22.60 34.45 23.85 33.20 25.37 33.20 C26.89 33.20 28.13 34.45 28.13 35.97 L28.13 46.60 Z M29.23 46.60 L29.23 35.97 C29.23 34.45 30.48 33.20 32.00 33.20 C33.52 33.20 34.77 34.45 34.77 35.97 L34.77 46.60 Z M35.87 46.60 L35.87 35.97 C35.87 34.45 37.11 33.20 38.63 33.20 C40.16 33.20 41.40 34.45 41.40 35.97 L41.40 46.60 Z";
const LEAF_L = "M32 54.4 C25.6 58.6 18.4 60.6 10.6 60.8 C17.2 63.6 26.4 62.0 32 58.0 Z";
const LEAF_R = "M32 54.4 C38.4 58.6 45.6 60.6 53.4 60.8 C46.8 63.6 37.6 62.0 32 58.0 Z";
const SMALL_CRESCENT = "M34.346 12.806 A6.9 6.9 0 1 0 34.346 24.394 A5.8 5.8 0 0 1 34.346 12.806 Z";
const SMALL_ARCADE = "M23.20 46.80 L23.20 37.75 C23.20 35.58 24.98 33.80 27.15 33.80 C29.32 33.80 31.10 35.58 31.10 37.75 L31.10 46.80 Z M32.90 46.80 L32.90 37.75 C32.90 35.58 34.68 33.80 36.85 33.80 C39.02 33.80 40.80 35.58 40.80 37.75 L40.80 46.80 Z";
const ARCH_STROKE = 3.4;
const SMALL_ARCH_STROKE = 4.6;

/** `ink: null` means the gold gradient rather than a flat colour. */
const TONES: Record<LogoTone, { plate: string | null; ink: string | null }> = {
  full: { plate: "#0F3D34", ink: null },
  dark: { plate: "#0A2A24", ink: null },
  light: { plate: "#F5F2E9", ink: "#7A5E15" },
  gold: { plate: null, ink: "#D4AF37" },
  monochrome: { plate: null, ink: "currentColor" },
};

const GOLD_RAMP = ["#F0DFA8", "#E0C264", "#D4AF37", "#A8811F"] as const;

export interface FiSabilillahLogoProps {
  variant?: LogoVariant;
  tone?: LogoTone;
  size?: LogoSize;
  /**
   * Omit when something adjacent already names the application. A logo repeated
   * to a screen reader on every page is noise, not access.
   */
  title?: string | null;
  className?: string;
}

function Emblem({ ink, small }: { ink: string; small: boolean }) {
  if (small) {
    return (
      <>
        <path d={ARCH} fill="none" stroke={ink} strokeWidth={SMALL_ARCH_STROKE} strokeLinejoin="round" />
        <path d={SMALL_CRESCENT} fill={ink} />
        <path d={SMALL_ARCADE} fill={ink} />
      </>
    );
  }
  return (
    <>
      <path d={ARCH} fill="none" stroke={ink} strokeWidth={ARCH_STROKE} strokeLinejoin="round" />
      <path d={ARCH_KEYLINE} fill="none" stroke={ink} strokeWidth={0.9} opacity={0.72} />
      <path d={CRESCENT} fill={ink} />
      <path d={STAR} fill={ink} />
      <path d={ARCADE} fill={ink} />
      <path d={LEAF_L} fill={ink} />
      <path d={LEAF_R} fill={ink} />
    </>
  );
}

export function FiSabilillahLogo({
  variant = "horizontal",
  tone = "full",
  size = "md",
  title = "Fi Sabilillah",
  className,
}: FiSabilillahLogoProps) {
  const px = EMBLEM_HEIGHT[size];
  const t = TONES[variant === "monochrome" ? "monochrome" : tone];
  // React's ids contain colons, which are legal in an id attribute but break the
  // moment anything tries to select one. Stripped, because a gradient that
  // resolves everywhere except in one CSS query is a bug that takes an afternoon.
  const gid = "fs" + React.useId().replace(/:/g, "");

  // The variant asked for is not always the variant that should be drawn. A
  // "horizontal" logo at 16px is a wordmark nobody can read beside a mark nobody
  // can see, so small sizes collapse to the icon whatever the caller wanted.
  const effective: LogoVariant =
    px < SIMPLIFY_BELOW && variant !== "wordmark" ? "icon" : variant;
  const small = px < SIMPLIFY_BELOW;

  const a11y = title
    ? { role: "img" as const, "aria-label": title }
    : { "aria-hidden": true as const, focusable: false as const };

  if (effective === "icon" || effective === "compact") {
    const ink = t.ink ?? `url(#${gid})`;
    return (
      <svg viewBox="0 0 64 64" width={px} height={px} className={className} {...a11y}>
        {title && <title>{title}</title>}
        {t.ink === null && (
          <defs>
            <linearGradient id={gid} x1="0.15" y1="0" x2="0.6" y2="1">
              {GOLD_RAMP.map((c, i) => (
                <stop key={c} offset={`${[0, 30, 66, 100][i]}%`} stopColor={c} />
              ))}
            </linearGradient>
          </defs>
        )}
        {t.plate && <rect width="64" height="64" rx="14.08" fill={t.plate} />}
        <g transform="translate(2.299,2.345) scale(0.92816)">
          <Emblem ink={ink} small={small} />
        </g>
      </svg>
    );
  }

  // The lockups need the drawn letterforms, which live in the generated SVGs
  // rather than inline: twelve glyphs of path data would triple this file and
  // would be a second copy free to drift from `brand/logo/*.svg`.
  const href = {
    horizontal: "/brand/logo/fi-sabilillah-logo-horizontal.svg",
    stacked: "/brand/logo/fi-sabilillah-logo-stacked.svg",
    wordmark: "/brand/logo/fi-sabilillah-wordmark.svg",
    monochrome: "/brand/logo/fi-sabilillah-logo-horizontal-mono.svg",
    icon: "/brand/logo/fi-sabilillah-icon-primary.svg",
    compact: "/brand/logo/fi-sabilillah-icon-primary.svg",
  }[effective];

  // Ratios measured off the generated files, not guessed: the wordmark is
  // 12.65 cap-heights wide, and a lockup sized by eye is a lockup that
  // overflows something.
  const heightFor: Partial<Record<LogoVariant, number>> = {
    horizontal: px * 1.17,
    stacked: px * 1.95,
    wordmark: px * 0.48,
  };

  return (
    <img
      src={tone === "light" ? href.replace(".svg", "-light.svg") : href}
      alt={title ?? ""}
      height={heightFor[effective] ?? px}
      className={className}
      {...(title ? {} : { "aria-hidden": true })}
    />
  );
}

export default FiSabilillahLogo;
