package org.fisabilillah.app.ui.brand

import androidx.compose.animation.core.Animatable
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.alpha
import androidx.compose.ui.draw.scale
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ColorFilter
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import org.fisabilillah.app.R
import org.fisabilillah.app.ui.theme.FiSabilillahTheme

/**
 * # The mark, in the application
 *
 * Every composable here draws `R.drawable.brand_emblem` or `R.drawable.brand_wordmark`,
 * both generated by `tools/brand/build.py` from the same geometry as every SVG and PNG
 * under `brand/`. Nothing in this file contains a path of its own, which is the only way
 * the app and the brand sheet stay in step through the next revision.
 *
 * ## Where the logo goes, and where it does not
 *
 * The full lockup appears in exactly three places: the landing screen, the sign-in screen
 * and the splash. Everywhere else the emblem alone identifies the application — a top bar
 * carrying the wordmark on every screen is a product reminding you whose it is, which is
 * the opposite of the calm this system is meant to hold.
 */

/** The tone the mark is drawn in. */
internal enum class BrandTone {
    /** Ivory arch, brass opening. For the brand grounds: splash, landing, sign-in. */
    OnBrand,

    /** Drawn in the product palette so it belongs to the screen rather than sitting on it. */
    InProduct,

    /** One colour, taken from the caller. Notifications, dense lists, disabled states. */
    Monochrome,
}

@Composable
private fun archColour(tone: BrandTone, mono: Color): Color = when (tone) {
    BrandTone.OnBrand -> BrandPalette.Ivory
    BrandTone.InProduct -> androidx.compose.material3.MaterialTheme.colorScheme.onSurface
    BrandTone.Monochrome -> mono
}

/**
 * The emblem alone.
 *
 * Below 32.dp the small cut is used: the middle arch closes up against the other two at
 * that size and the mark turns into a smudge. The switch is automatic because leaving it
 * to the caller means it will be got wrong exactly once, in a notification, at 24dp.
 */
@Composable
internal fun BrandEmblem(
    modifier: Modifier = Modifier,
    size: Dp = 40.dp,
    tone: BrandTone = BrandTone.OnBrand,
    monochromeColour: Color = Color.Unspecified,
    /** Null when the mark is decorative and something else already names the app. */
    contentDescription: String? = null,
) {
    val small = size < 32.dp
    val arch = archColour(tone, monochromeColour)
    Image(
        painter = painterResource(
            if (small) R.drawable.brand_emblem_small else R.drawable.brand_emblem,
        ),
        contentDescription = contentDescription,
        modifier = modifier
            .size(size)
            .then(if (contentDescription == null) Modifier.clearAndSetSemantics { } else Modifier),
        colorFilter = if (tone == BrandTone.Monochrome) ColorFilter.tint(arch) else null,
    )
}

/**
 * Emblem and wordmark, side by side.
 *
 * The wordmark is a drawable rather than a `Text`, so it cannot be re-flowed, re-weighted
 * or scaled by the system font setting. That is the one place in this application where
 * ignoring the user's text size is correct: a logo is an image of a word, not a word.
 * Every actual sentence in the app still scales.
 */
@Composable
internal fun BrandLockup(
    modifier: Modifier = Modifier,
    emblemSize: Dp = 44.dp,
    tone: BrandTone = BrandTone.OnBrand,
    monochromeColour: Color = Color.Unspecified,
) {
    val spacing = FiSabilillahTheme.spacing
    val wordColour = archColour(tone, monochromeColour)
    Row(
        modifier = modifier.clearAndSetSemantics {
            contentDescription = "Fi Sabilillah"
        },
        verticalAlignment = Alignment.CenterVertically,
    ) {
        BrandEmblem(size = emblemSize, tone = tone, monochromeColour = monochromeColour)
        Spacer(Modifier.width(spacing.sm))
        Image(
            painter = painterResource(R.drawable.brand_wordmark),
            contentDescription = null,
            colorFilter = ColorFilter.tint(wordColour),
            modifier = Modifier.height(emblemSize * 0.40f),
        )
    }
}

/** Emblem over wordmark. Splash, and the empty state of an unauthenticated screen. */
@Composable
internal fun BrandLockupStacked(
    modifier: Modifier = Modifier,
    emblemSize: Dp = 96.dp,
    tone: BrandTone = BrandTone.OnBrand,
    monochromeColour: Color = Color.Unspecified,
) {
    val spacing = FiSabilillahTheme.spacing
    Column(
        modifier = modifier.clearAndSetSemantics { contentDescription = "Fi Sabilillah" },
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        BrandEmblem(size = emblemSize, tone = tone, monochromeColour = monochromeColour)
        Spacer(Modifier.height(spacing.md))
        Image(
            painter = painterResource(R.drawable.brand_wordmark),
            contentDescription = null,
            colorFilter = ColorFilter.tint(archColour(tone, monochromeColour)),
            modifier = Modifier.height(emblemSize * 0.20f),
        )
    }
}

/**
 * The splash.
 *
 * The motion is one gesture: the mark fades up and settles from 96% to 100% over 520ms on
 * the Amanah decelerating curve, and stops. It does not bounce, spin, pulse, sparkle or
 * loop, and there is no progress indicator because the app has nothing honest to report a
 * percentage of.
 *
 * Under reduced motion the whole thing is a cut — [Motion.scaled] returns zero and the
 * mark is simply present. That is deliberate rather than a shortened animation: somebody
 * who has asked the system for no motion has asked for no motion.
 */
@Composable
internal fun BrandSplash(
    modifier: Modifier = Modifier,
    reducedMotion: Boolean = false,
) {
    val motion = FiSabilillahTheme.motion
    val duration = if (reducedMotion) 0 else 520
    val progress = remember { Animatable(if (duration == 0) 1f else 0f) }

    LaunchedEffect(duration) {
        if (duration > 0) {
            progress.animateTo(1f, tween(durationMillis = duration, easing = motion.easing))
        }
    }

    Box(
        modifier = modifier
            .fillMaxSize()
            .background(BrandPalette.SabilGreenDeep),
        contentAlignment = Alignment.Center,
    ) {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center,
            modifier = Modifier
                .alpha(progress.value)
                .scale(0.96f + 0.04f * progress.value),
        ) {
            BrandLockupStacked(emblemSize = 112.dp, tone = BrandTone.OnBrand)
        }
    }
}

/**
 * The brand palette, as Compose colours.
 *
 * Distinct from `ui/theme/Color.kt`, which is the *product* palette. A brand colour has to
 * survive an app-store grid and a printed leaflet; a product colour has to carry a hundred
 * states of meaning across hundreds of screens. Values are generated into
 * `brand/tokens/brand-tokens.json` and restated here.
 */
internal object BrandPalette {
    val SabilGreen = Color(0xFF0B3A30)
    val SabilGreenDeep = Color(0xFF072A22)
    val MineralGreen = Color(0xFF1F5A4C)
    val Sage = Color(0xFF7FA98C)

    /** On dark grounds only. 5.44:1 on Sabil Green; 2.06:1 on ivory, which is unusable. */
    val Brass = Color(0xFFC6A664)

    /** The accent for light grounds. 4.87:1 on ivory. */
    val BrassDeep = Color(0xFF836427)

    val Ivory = Color(0xFFF4F1E8)
    val Charcoal = Color(0xFF0C1013)
}
