package org.fisabilillah.app.ui.brand

import androidx.compose.animation.core.Animatable
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.alpha
import androidx.compose.ui.draw.scale
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ColorFilter
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import org.fisabilillah.app.R
import org.fisabilillah.app.ui.theme.FiSabilillahTheme

/**
 * # The mark, in the application
 *
 * Every composable here draws `R.drawable.brand_emblem` or `R.drawable.brand_wordmark`,
 * both generated by `tools/brand/build.py` from the same geometry as every SVG and PNG
 * under `brand/`. Nothing in this file contains a path of its own, which is the only way
 * the app and the brand sheet stay in step through the next revision.
 *
 * ## Where the logo goes, and where it does not
 *
 * The full lockup appears in exactly three places: the landing screen, the sign-in screen
 * and the splash. Everywhere else the emblem alone identifies the application — a top bar
 * carrying the wordmark on every screen is a product reminding you whose it is, which is
 * the opposite of the calm this system is meant to hold.
 */

/** The tone the mark is drawn in. */
internal enum class BrandTone {
    /** Gold mark, ivory word. For the brand grounds: splash, landing, sign-in. */
    OnBrand,

    /** Drawn in the product palette so it belongs to the screen rather than sitting on it. */
    InProduct,

    /** One colour, taken from the caller. Notifications, dense lists, disabled states. */
    Monochrome,
}

/**
 * How much wider than tall `brand_wordmark` is — 1267.25 / 102, straight off the generated
 * drawable's viewport.
 *
 * Every wordmark size below is expressed as a fraction of the emblem and then divided by
 * this, so the two lockups keep the emblem-to-word ratio the brand sheet uses (roughly 6:1
 * beside the mark, 2.9:1 under it) and so nothing overflows a 320dp screen. A wordmark
 * sized by eye is how a lockup ends up correct on the reviewer's phone and clipped on the
 * cheapest one.
 */
private const val WORDMARK_ASPECT = 12.42f

@Composable
private fun archColour(tone: BrandTone, mono: Color): Color = when (tone) {
    BrandTone.OnBrand -> BrandPalette.Ivory
    BrandTone.InProduct -> androidx.compose.material3.MaterialTheme.colorScheme.onSurface
    BrandTone.Monochrome -> mono
}

/**
 * The emblem alone.
 *
 * Below 32.dp the small cut is used: it drops the arch's inner keyline, the star and the
 * two leaf sweeps, thickens what is left, and keeps the crescent and a two-arch arcade.
 * Those three details are under a pixel wide at 24dp, and detail you cannot resolve does
 * not read as detail — it reads as a smudge over the parts that were legible.
 *
 * The switch is automatic because leaving it to the caller means it will be got wrong
 * exactly once, in a notification, at 24dp.
 */
@Composable
internal fun BrandEmblem(
    modifier: Modifier = Modifier,
    size: Dp = 40.dp,
    tone: BrandTone = BrandTone.OnBrand,
    monochromeColour: Color = Color.Unspecified,
    /** Null when the mark is decorative and something else already names the app. */
    contentDescription: String? = null,
) {
    val small = size < 32.dp
    val arch = archColour(tone, monochromeColour)
    Image(
        painter = painterResource(
            if (small) R.drawable.brand_emblem_small else R.drawable.brand_emblem,
        ),
        contentDescription = contentDescription,
        modifier = modifier
            .size(size)
            .then(if (contentDescription == null) Modifier.clearAndSetSemantics { } else Modifier),
        colorFilter = if (tone == BrandTone.Monochrome) ColorFilter.tint(arch) else null,
    )
}

/**
 * Emblem and wordmark, side by side.
 *
 * The wordmark is a drawable rather than a `Text`, so it cannot be re-flowed, re-weighted
 * or scaled by the system font setting. That is the one place in this application where
 * ignoring the user's text size is correct: a logo is an image of a word, not a word.
 * Every actual sentence in the app still scales.
 */
@Composable
internal fun BrandLockup(
    modifier: Modifier = Modifier,
    emblemSize: Dp = 36.dp,
    tone: BrandTone = BrandTone.OnBrand,
    monochromeColour: Color = Color.Unspecified,
) {
    val spacing = FiSabilillahTheme.spacing
    val wordColour = archColour(tone, monochromeColour)
    Row(
        modifier = modifier.clearAndSetSemantics {
            contentDescription = "Fi Sabilillah"
        },
        verticalAlignment = Alignment.CenterVertically,
    ) {
        BrandEmblem(size = emblemSize, tone = tone, monochromeColour = monochromeColour)
        Spacer(Modifier.width(spacing.sm))
        Image(
            painter = painterResource(R.drawable.brand_wordmark),
            contentDescription = null,
            colorFilter = ColorFilter.tint(wordColour),
            // Six emblems wide, as on the brand sheet — but `weight(fill = false)` and a
            // Fit scale mean that when the caller asks for an emblem too large for the
            // screen, the word shrinks to the space there is instead of running off the
            // right edge. A lockup that clips is worse than a lockup that is small.
            contentScale = ContentScale.Fit,
            modifier = Modifier
                .weight(1f, fill = false)
                .height(emblemSize * 6f / WORDMARK_ASPECT),
        )
    }
}

/** Emblem over wordmark. Splash, and the empty state of an unauthenticated screen. */
@Composable
internal fun BrandLockupStacked(
    modifier: Modifier = Modifier,
    emblemSize: Dp = 88.dp,
    tone: BrandTone = BrandTone.OnBrand,
    monochromeColour: Color = Color.Unspecified,
) {
    val spacing = FiSabilillahTheme.spacing
    Column(
        modifier = modifier.clearAndSetSemantics { contentDescription = "Fi Sabilillah" },
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        BrandEmblem(size = emblemSize, tone = tone, monochromeColour = monochromeColour)
        Spacer(Modifier.height(spacing.md))
        Image(
            painter = painterResource(R.drawable.brand_wordmark),
            contentDescription = null,
            colorFilter = ColorFilter.tint(archColour(tone, monochromeColour)),
            // Two and nine-tenths emblems wide, as on the brand sheet, shrinking to fit
            // for the same reason as the horizontal lockup.
            contentScale = ContentScale.Fit,
            modifier = Modifier
                .fillMaxWidth()
                .height(emblemSize * 2.9f / WORDMARK_ASPECT),
        )
    }
}

/**
 * The splash.
 *
 * The motion is one gesture: the mark fades up and settles from 96% to 100% over 520ms on
 * the Amanah decelerating curve, and stops. It does not bounce, spin, pulse, sparkle or
 * loop, and there is no progress indicator because the app has nothing honest to report a
 * percentage of.
 *
 * Under reduced motion the whole thing is a cut — [Motion.scaled] returns zero and the
 * mark is simply present. That is deliberate rather than a shortened animation: somebody
 * who has asked the system for no motion has asked for no motion.
 */
@Composable
internal fun BrandSplash(
    modifier: Modifier = Modifier,
    reducedMotion: Boolean = false,
) {
    val motion = FiSabilillahTheme.motion
    val duration = if (reducedMotion) 0 else 520
    val progress = remember { Animatable(if (duration == 0) 1f else 0f) }

    LaunchedEffect(duration) {
        if (duration > 0) {
            progress.animateTo(1f, tween(durationMillis = duration, easing = motion.easing))
        }
    }

    Box(
        modifier = modifier
            .fillMaxSize()
            .background(BrandPalette.ForestDeep),
        contentAlignment = Alignment.Center,
    ) {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center,
            modifier = Modifier
                .alpha(progress.value)
                .scale(0.96f + 0.04f * progress.value),
        ) {
            BrandLockupStacked(tone = BrandTone.OnBrand)
        }
    }
}

/**
 * The brand palette, as Compose colours.
 *
 * Distinct from `ui/theme/Color.kt`, which is the *product* palette. A brand colour has to
 * survive an app-store grid and a printed leaflet; a product colour has to carry a hundred
 * states of meaning across hundreds of screens. Values are generated into
 * `brand/tokens/brand-tokens.json` and restated here.
 */
internal object BrandPalette {
    /** The ground. Every lockup, every icon, the splash. */
    val DeepGreen = Color(0xFF0F3D34)

    /** One step down, for the splash and anywhere the ground needs to recede. */
    val ForestDeep = Color(0xFF0A2A24)

    val Mineral = Color(0xFF1C574A)
    val Sage = Color(0xFF6BAA7D)

    /**
     * The accent, and only ever an accent.
     *
     * 6.19:1 on Deep Green, so it is legible as the mark and as the tagline. It is
     * 2.12:1 on ivory, which is unusable — [GoldDeep] is the light-ground substitute,
     * and there is no case where picking between them is left to the caller's eye.
     */
    val Gold = Color(0xFFD4AF37)

    /** The accent for light grounds. 4.83:1 on ivory. */
    val GoldDeep = Color(0xFF7A5E15)

    val Ivory = Color(0xFFF5F2E9)
    val Charcoal = Color(0xFF0D1115)
}
