// Generated by tools/brand/build.py. Do not edit.
export const brandTokens = {
  "deep-green": "#0F3D34",
  "forest-deep": "#0A2A24",
  "mineral": "#1C574A",
  "sage": "#6BAA7D",
  "gold": "#D4AF37",
  "gold-deep": "#7A5E15",
  "ivory": "#F5F2E9",
  "charcoal": "#0D1115",
  "stone": "#68757A",
} as const;

export const functionalTokens = {
  "success": "#3E7A5E",
  "warning": "#AF7A2A",
  "danger": "#A04B55",
  "learning": "#6C638E",
  "service": "#246F6C",
  "neutral": "#68757A",
} as const;

export const goldRamp = ["#F0DFA8", "#E0C264", "#D4AF37", "#A8811F"] as const;

export type BrandToken = keyof typeof brandTokens;
