// Generated by tools/brand/build.py. Do not edit.
export const brandTokens = {
  "sabil-green": "#0B3A30",
  "sabil-green-deep": "#072A22",
  "mineral-green": "#1F5A4C",
  "sage": "#7FA98C",
  "brass": "#C6A664",
  "brass-deep": "#836427",
  "ivory": "#F4F1E8",
  "charcoal": "#0C1013",
  "stone": "#64727C",
} as const;

export const functionalTokens = {
  "success": "#3E7A5E",
  "warning": "#AF7A2A",
  "danger": "#A04B55",
  "learning": "#6C638E",
  "service": "#246F6C",
  "neutral": "#64727C",
} as const;

export type BrandToken = keyof typeof brandTokens;
