"""
Fi Sabilillah — the emblem, as exact geometry on a 0 0 64 64 grid.

THIS FOLLOWS THE SUPPLIED REFERENCE. It is not an interpretation of it.

Every path is computed rather than traced. That is what lets one source produce
an SVG, an Android VectorDrawable, an iOS PNG and a React component that are the
*same shape* rather than four drawings of it, and it is why a change to the mark
is a change to one number rather than a morning in an editor.

THE SILHOUETTE

An onion arch: pointed finial, an ogee flare to the shoulder, near-straight
flanks, then a taper to a soft point at the foot. Drawn as a band -- one stroked
path at [ARCH_STROKE] -- which gives a uniform gold ribbon on every renderer and
scales without the two edges of a filled band drifting apart.

Inside it: a keyline, a crescent and star, and the calligraphy (set in
`letters.py`, from a real Arabic typeface, shaped by HarfBuzz). Beneath it, two
leaf sweeps whose tips turn up and out.

SYMMETRY IS STRUCTURAL, NOT TYPED

Every arch below is authored as its right-hand half and mirrored by [_mirror].
Typing both halves is how a mark ends up 0.1 units lopsided three revisions
later, in a way nobody can see and everybody can feel.

WHY THE NUMBERS LOOK ARBITRARY

They are measured off the reference. The apex sits at y=3.6 and the shoulder at
y=25.8 because that is the reference's finial-to-shoulder relationship; move
either by half a unit and an onion arch becomes a teardrop.
"""
import math

VIEWBOX = 64
CENTRE = 32.0


def _mirror(apex_y, half):
    """
    A closed, exactly symmetrical arch.

    `half` is the right-hand side, apex downward, as `(c1, c2, end)` cubics. The
    left side is generated by reflecting each control point about x=32 and
    walking back up, so the two halves are the same numbers by construction.
    """
    d = [f"M{CENTRE:g} {apex_y:g}"]
    for c1, c2, end in half:
        d.append(f"C{c1[0]:g} {c1[1]:g} {c2[0]:g} {c2[1]:g} {end[0]:g} {end[1]:g}")
    prev_ends = [(CENTRE, apex_y)] + [e for _, _, e in half]
    for i in range(len(half) - 1, -1, -1):
        c1, c2, _end = half[i]
        back = prev_ends[i]
        d.append(f"C{2 * CENTRE - c2[0]:g} {c2[1]:g} {2 * CENTRE - c1[0]:g} {c1[1]:g} "
                 f"{2 * CENTRE - back[0]:g} {back[1]:g}")
    d.append("Z")
    return " ".join(d)


# ── The band ─────────────────────────────────────────────────────────────────

ARCH = _mirror(3.6, [
    ((33.8, 6.2), (35.8, 8.6), (37.8, 11.2)),      # the finial's flank
    ((41.8, 16.2), (45.4, 20.2), (45.4, 25.8)),    # the ogee out to the shoulder
    ((45.4, 31.0), (45.3, 35.4), (45.0, 39.6)),    # the near-straight flank
    ((44.6, 45.6), (39.4, 51.4), (32.0, 54.8)),    # the taper to the foot
])
ARCH_STROKE = 4.0

# The same silhouette, filled, sitting under the band: the dark field the
# crescent and the calligraphy are read against. Inset by half the band width so
# it meets the band's inner edge and no hairline of plate shows between them.
FIELD = _mirror(6.0, [
    ((33.6, 8.4), (35.2, 10.4), (36.9, 12.6)),
    ((40.4, 17.0), (43.4, 20.6), (43.4, 25.9)),
    ((43.4, 30.8), (43.3, 35.0), (43.0, 39.2)),
    ((42.7, 44.4), (38.2, 49.4), (32.0, 52.4)),
])

# A second, thinner arch inside the field. The reference has it, and it is what
# turns an outline into a doorway: one line reads as a shape, two read as depth.
ARCH_KEYLINE = _mirror(8.0, [
    ((33.4, 10.4), (34.8, 12.2), (36.2, 14.2)),
    ((39.3, 18.2), (41.9, 21.4), (41.9, 26.1)),
    ((41.9, 30.5), (41.8, 34.4), (41.5, 38.2)),
    ((41.2, 42.9), (37.3, 47.4), (32.0, 50.1)),
])
KEYLINE_STROKE = 0.85


# ── Crescent and star ────────────────────────────────────────────────────────

def _crescent(cx, cy, R, d, r):
    """
    A crescent as two exact arcs, from the intersection of two circles.

    Not two circles resolved with an even-odd fill: that renders as a near-solid
    disc in some rasterisers, and where it does work the horns come out as blunt
    stubs. Two arcs are one path, are exact, and survive into a VectorDrawable.

    R  radius of the disc; r  radius of the bite; d  distance between centres.
    """
    a = (d * d - r * r + R * R) / (2 * d)
    h = math.sqrt(R * R - a * a)
    return (f"M{cx + a:.3f} {cy - h:.3f} "
            f"A{R} {R} 0 1 0 {cx + a:.3f} {cy + h:.3f} "
            f"A{r} {r} 0 0 1 {cx + a:.3f} {cy - h:.3f} Z")


def _star(cx, cy, R, points=5, ratio=0.44, phase=-math.pi / 2):
    """A five-pointed star, point-up, sitting off the crescent's upper horn."""
    pts = []
    for i in range(points * 2):
        rad = R if i % 2 == 0 else R * ratio
        a = phase + i * math.pi / points
        pts.append(f"{cx + rad * math.cos(a):.2f} {cy + rad * math.sin(a):.2f}")
    return "M" + " L".join(pts) + " Z"


CRESCENT = _crescent(cx=29.9, cy=20.6, R=4.9, d=2.9, r=4.1)
STAR = _star(cx=35.0, cy=17.4, R=2.2)


# ── Where the calligraphy sits ───────────────────────────────────────────────
#
# The box `letters.calligraphy_path` fits the shaped Arabic into. Narrower than
# the field, because the field tapers and a rectangle inscribed in a taper has to
# clear the narrow end rather than the wide one.
#
# Nothing in this module knows what the phrase says, which is the point: the
# geometry does not get a vote on the Arabic.

CALLIGRAPHY_BOX = (24.9, 28.4, 39.1, 44.6)


# ── Leaves ───────────────────────────────────────────────────────────────────
#
# Two sweeps from behind the foot of the arch, out and then up: a cradle, not a
# pair of drips. The tip turning upward is the whole difference between "hands
# holding something" and "something running off the bottom of the mark", and
# after the arch it is the detail the reference is most recognisable by.

LEAF_R = ("M32 51 C38.6 51.8 44.6 53.6 49 56.4 "
          "C50.8 57.5 52.2 56.6 51.6 54.8 "
          "C49.8 49.8 41.8 46.6 32 48 Z")
LEAF_L = ("M32 51 C25.4 51.8 19.4 53.6 15 56.4 "
          "C13.2 57.5 11.8 56.6 12.4 54.8 "
          "C14.2 49.8 22.2 46.6 32 48 Z")


# ── The small cut ────────────────────────────────────────────────────────────
#
# Below 32px the keyline is a fifth of a pixel, the star is three pixels of
# noise beside the moon, the curled leaf tips turn to mush, and the calligraphy
# -- which is the thing that most needs to be legible or absent -- becomes a
# grey smear. Detail you cannot resolve does not read as detail; it reads as
# dirt over the parts that were legible.
#
# So the small cut is the arch, a larger crescent and star that now have the
# whole field to themselves, and one uncurled sweep a side.

SMALL_ARCH_STROKE = 5.2
SMALL_CRESCENT = _crescent(cx=30.2, cy=25.6, R=8.0, d=4.6, r=6.7)
SMALL_STAR = _star(cx=38.4, cy=20.4, R=3.3)
SMALL_LEAF_R = ("M32 54 C39.6 55.4 47 58 52.6 61.6 C50 54.4 41.6 50.4 32 51 Z")
SMALL_LEAF_L = ("M32 54 C24.4 55.4 17 58 11.4 61.6 C14 54.4 22.4 50.4 32 51 Z")


# ── The ink box ──────────────────────────────────────────────────────────────
#
# Computed from the paths, not typed in. The band's stroke pushes past the
# silhouette by half its width on every side and the leaf tips run wider and
# lower than the arch does, so the mark does not fill its own 64-unit square --
# and an icon laid out on the square rather than on the ink puts the leaf tips
# into the launcher's corner radius.
#
# It is computed rather than measured-and-hardcoded because a hardcoded box is
# correct exactly until the next time somebody nudges a leaf.

def _bbox(d, pad=0.0):
    from svgpathtools import parse_path
    x0, x1, y0, y1 = parse_path(d).bbox()
    return (x0 - pad, y0 - pad, x1 + pad, y1 + pad)


def _union(boxes):
    return (min(b[0] for b in boxes), min(b[1] for b in boxes),
            max(b[2] for b in boxes), max(b[3] for b in boxes))


INK = _union([
    _bbox(ARCH, ARCH_STROKE / 2), _bbox(LEAF_L), _bbox(LEAF_R),
    _bbox(CRESCENT), _bbox(STAR),
])

# How much of Android's 108dp adaptive viewport the mark occupies.
#
# 0.50 rather than the 0.62 that looks right in a preview, because the launcher
# only guarantees the central **66dp circle** and crops the rest to whatever
# shape the OEM prefers. The mark is a tall arch with leaves at the foot, so its
# widest-from-centre points are the leaf tips, and at 0.62 they sit 40.6dp out --
# comfortably inside a square mask and clipped by a circular one.
#
# This lives here, next to the geometry it depends on, because `build.py` places
# the icon with it and `validate.py` checks the icon against it, and the two
# quietly disagreeing is exactly how an icon ships cropped.
ADAPTIVE_MARGIN = 0.50
SAFE_RADIUS_DP = 33.0

SMALL_INK = _union([
    _bbox(ARCH, SMALL_ARCH_STROKE / 2), _bbox(SMALL_LEAF_L), _bbox(SMALL_LEAF_R),
    _bbox(SMALL_CRESCENT), _bbox(SMALL_STAR),
])
